defaults:
  generation:
    temperature: 0.0
    repetition_penalty: 1.0
    presence_penalty: 0.0
    num_return_sequences: 1

tasks:
  - name: translation
    datasets:
      - darumeru/flores_ru_en
      - darumeru/flores_en_ru
    max_sample_per_dataset: 200
    few_shot_count: 5
      
  - name: summarization
    datasets:
      - daru/treewayabstractive
      - ilyagusev/gazeta
    max_sample_per_dataset: 200
    few_shot_count: 5

  - name: shlepa
    datasets:
      - shlepa/moviesmc
      - shlepa/musicmc
      - shlepa/lawmc
      - shlepa/booksmc
    few_shot_count: 5

  - name: nlpcoreteam_mmlu_ru_few_shot
    datasets:
      - nlpcoreteam/rummlu
    few_shot_count: 5
    name_suffix: few_shot

  - name: nlpcoreteam_mmlu_en_few_shot
    datasets:
      - nlpcoreteam/enmmlu
    few_shot_count: 5
    name_suffix: few_shot

  - name: internal_copy
    datasets:
      - darumeru/cp_para_ru
      - darumeru/cp_para_en
      - darumeru/cp_doc_ru
    max_len: 16000
    few_shot_count: 5
    max_sample_per_dataset: 200

  - name: ner
    datasets:
      - RCC-MSU/collection3-(in-place)
    few_shot_count: 5
    max_sample_per_dataset: 200

  - name: classification
    datasets:
      - sentiment_kinopoisk
      - russiannlp/rucola_custom
    few_shot_count: 5
    max_sample_per_dataset: 200